### PR TITLE
Friendship Version 2

### PR DESCRIPTION
**Pull request by sinansevgi**
For this milestone, our task was improving our friendship model with the 2 rows mutual friendship model. (https://explainextended.com/2009/03/07/selecting-friends/)
We already implemented the friendship model with two rows on the previous milestone. 
We really appreciate any feedback.

### CODE REVIEW

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🔧 
### Hi There ✋🏽
Amazing work you have here. You have done a great job so far with the Social- Scaffold project. 
However, there is a problem with your migrations. I am unable to run the complete migrate when I run the command `rails db:migrate`. The following are the errors I get from the pending migrations:

```
$ rails db:migrate
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "users" already exists
: CREATE TABLE "users" ("id" bigserial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
C:/Users/PC/Desktop/TSE/ror-social-scaffold/db/migrate/20200130195710_devise_create_users.rb:5:in `change'
bin/rails:11:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "users" already exists
: CREATE TABLE "users" ("id" bigserial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
C:/Users/PC/Desktop/TSE/ror-social-scaffold/db/migrate/20200130195710_devise_create_users.rb:5:in `change'
bin/rails:11:in `<main>'

Caused by:
PG::DuplicateTable: ERROR:  relation "users" already exists
C:/Users/PC/Desktop/TSE/ror-social-scaffold/db/migrate/20200130195710_devise_create_users.rb:5:in `change'
bin/rails:11:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20200130195710 DeviseCreateUsers: migrating ================================
-- create_table(:users)
```
You seem to be having a duplicated migration table for `users`.

Please kindly look into the above error. You can try mimicking it by cloning your repo and running the migrations again.
Feel free to reach out to me on slack if you have any questions, **_Witah Georjane_** 🤝 

Good luck on your project and Happy Coding 💻

**Comment by sinansevgi** [comment]
Thank you for your review. This means you already have a database with the same name and same tables. Please flush your database before checking projects or use docker or vagrant to create abstracted environments for each project. [This](https://www.freecodecamp.org/news/painless-rails-development-environment-setup-with-docker/) guide is really helpful.

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made huge progress in this milestone. I like the way you abstracted all your view-related logic into the helper module :+1: 
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Some things are not in order with your logic. Here's the expected flow of the mutual friendship model: given two(2) users, say User1 and User2:
- When User1 sends a friend request to User2, a single record (row) is created on the friendship table, with User1 id as user_id and User2 id as friend_id, then the status column will be set to `false` by default.
- when friendship is confirmed by User2, an additional row with reversed user-friend pair is created. e.g.
```ruby 
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- thanks to this, we can find User1 friends only by user_id in the friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- in order to get all posts written by a user on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerables)
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
- [x] Posts timeline includes posts written by a logged-in user and **their friends**.
- **their friends** here means friends that already accepted the user's friend request
- At the moment, the posts timeline displays posts written by a user and both their friends that already accepted the invitation and the ones that have not accepted the user invitation.

**[ COMMENTS ]**

- In the project specification for this milestone, you're told that during the code review, you will get hints about implementing mutual friendships in the most efficient way. Therefore, the above method is the most efficient way as mentioned earlier.
- Note that you're to understand the method above and use it to improve your own method. However, this does not mean that you should completely refactor your codebase but if you do, you're not going to be penalized. 
- The above is the recommended flow. Please stick to it no matter the method you use.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [ ] You have grammar and spelling issues in Readme. Please use Grammarly to remove them. 
- [ ] [Optional] Please update About section of your repo. You can add what the project is about and what technologies you used

**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi Guys**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
